language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get code.google.com/p/go.crypto/ripemd160
  - go get code.google.com/p/go.tools/cmd/cover
  - wget -O aerospike-server.tgz http://aerospike.com/download/server/3.3.5/artifact/tgz
  - tar xvzf aerospike-server.tgz
  - cp -f .travis/aerospike.conf ./aerospike-server/share/etc
  - cd aerospike-server
  - mkdir instance1
  - mkdir instance2
  - ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
  - ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
  - cd instance1
  - sudo ./bin/aerospike start
  - cd ..
  - cd instance2
  - sudo ./bin/aerospike start
  - cd ../..
  - sleep 3

script:
  - go build tools/benchmark/benchmark.go
  - go build tools/asinfo/asinfo.go
  - go build tools/cli/cli.go
  - go build examples/simple.go
  - go build examples/blob.go
  - go build examples/info.go
  - ginkgo -cover -r -race -keepGoing -succinct -randomizeSuites
