language: go
go:
- 1.4
- tip
matrix:
  allow_failures:
  - go: tip
install:
- if [ -d "$HOME/gopath/src/github.com/citrusleaf" ]; then mv $HOME/gopath/src/github.com/citrusleaf
  $HOME/gopath/src/github.com/aerospike; fi
- export PATH=$PATH:$HOME/gopath/bin
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
- wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- mkdir instance1
- mkdir instance2
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
- cd instance1
- sudo ./bin/aerospike start
- cd ../..
- pwd
- sleep 5
- sudo tail -n 1000 aerospike-server/instance1/var/log/aerospike.log
script:
- find tools -name "*.go" -type f -exec go -- build {} ';'
- find examples -name "*.go" -type f -exec go -- build {} ';'
- ginkgo -cover -race -r -keepGoing -succinct -randomizeSuites
- cd aerospike-server/instance1
- sudo ./bin/aerospike restart
- cd ../instance2
- sudo ./bin/aerospike start
- cd ../..
- sleep 5
- ginkgo -cover -race -r -keepGoing -succinct -randomizeSuites
- .travis/proxy_check.sh
notifications:
  hipchat:
    rooms:
      secure: mGFpOr8JWxK0bYj6wK3ur5+qtsfK+Im1njfPgoQ2b/Sudlii/mr2QiHyQRHtstw7tr79nyoMYgQ1lc53pTxUNAVSI/PkTJTBaDE4ZkyUG5+UW8NgMsC6FYhRfgu0xq+SBNn5a6KbrL8puQq0FH6fjEDYC00QqmN5L/967WCxF8g=
  email:
  - qe-notices@aerospike.com
  - qe-notices-clients@aerospike.com
  slack:
    secure: FwRNnmQZLVD3ygwu66ujNTsy1rHKFAV01wZJCad+L0r5I54lxFWZxsO0JtRbhFyZ0yb4fhls4dPpczTqQrtlRgUzWW55u2i5T/bkTWxOik8QPJW35n9EvSOMYgiTQs1PQeSYwRmiqn0aDd8Fu1RAvB71nLKeyccYbVMHGyhpAq8=
